[target.xtensa-esp32-none-elf]
runner = "probe-rs run --chip=esp32 --always-print-stacktrace --no-location --catch-hardfault"

[env]

[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
]

target = "xtensa-esp32-none-elf"

[unstable]
build-std = ["alloc", "core"]
